/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // TALASH Design System — "Intelligent Atelier"
        'primary':                  '#4648d4',
        'primary-container':        '#6063ee',
        'primary-fixed':            '#e1e0ff',
        'primary-fixed-dim':        '#c0c1ff',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#fffbff',
        'on-primary-fixed':         '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'inverse-primary':          '#c0c1ff',
        'secondary':                '#5b598c',
        'secondary-container':      '#c7c3fe',
        'secondary-fixed':          '#e3dfff',
        'secondary-fixed-dim':      '#c4c1fb',
        'on-secondary':             '#ffffff',
        'on-secondary-container':   '#514f81',
        'on-secondary-fixed':       '#181445',
        'on-secondary-fixed-variant': '#444173',
        'tertiary':                 '#904900',
        'tertiary-container':       '#b55d00',
        'tertiary-fixed':           '#ffdcc5',
        'tertiary-fixed-dim':       '#ffb783',
        'on-tertiary':              '#ffffff',
        'on-tertiary-container':    '#fffbff',
        'on-tertiary-fixed':        '#301400',
        'on-tertiary-fixed-variant': '#703700',
        'error':                    '#ba1a1a',
        'error-container':          '#ffdad6',
        'on-error':                 '#ffffff',
        'on-error-container':       '#93000a',
        'surface':                  '#f7f9fb',
        'surface-dim':              '#d8dadc',
        'surface-bright':           '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f2f4f6',
        'surface-container':        '#eceef0',
        'surface-container-high':   '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant':          '#e0e3e5',
        'surface-tint':             '#494bd6',
        'on-surface':               '#191c1e',
        'on-surface-variant':       '#464554',
        'on-background':            '#191c1e',
        'background':               '#f7f9fb',
        'outline':                  '#767586',
        'outline-variant':          '#c7c4d7',
        'inverse-surface':          '#2d3133',
        'inverse-on-surface':       '#eff1f3',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        '2xl':   '0.75rem',
        full:    '9999px',
      },
      boxShadow: {
        'tonal': '0 4px 32px 0 rgba(70, 69, 84, 0.06)',
      },
    },
  },
  plugins: [],
}
