import PublicFooter from "@/components/public/PublicFooter";
import PublicNav from "@/components/public/PublicNav";

export default function TermsPage() {
  return (
    <div className="bg-surface text-on-surface min-h-screen flex flex-col">
      <PublicNav />

      <main className="flex-grow max-w-4xl mx-auto w-full px-6 py-12 md:py-20 pt-32">
        <article className="bg-surface-container-lowest rounded-2xl p-8 md:p-12 shadow-tonal border border-outline-variant/15">
          <header className="mb-12 border-b border-outline-variant/15 pb-8">
            <h1 className="text-[2.75rem] font-bold tracking-tight leading-tight text-on-surface mb-4">
              Terms of Service
            </h1>
            <p className="text-base font-medium text-on-surface-variant flex items-center gap-2">
              <span className="material-symbols-outlined text-[1.25rem]">
                calendar_today
              </span>
              Effective Date: January 2024
            </p>
          </header>

          <div className="space-y-8 text-sm leading-relaxed text-on-surface-variant">
            <section>
              <h2 className="text-2xl font-semibold tracking-tight text-on-surface mb-4">
                1. Acceptance of Terms
              </h2>
              <p className="mb-4">
                By accessing or using the Talash Insight platform
                (&quot;Service&quot;), you agree to be bound by these Terms of
                Service (&quot;Terms&quot;). If you do not agree to these Terms,
                you may not access or use the Service.
              </p>
              <p>
                These Terms constitute a legally binding agreement between you
                (whether personally or on behalf of an entity) and Talash
                Insight (&quot;Company&quot;, &quot;we&quot;, &quot;us&quot;, or
                &quot;our&quot;), concerning your access to and use of the
                platform.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold tracking-tight text-on-surface mb-4">
                2. Institutional Use &amp; Accounts
              </h2>
              <p className="mb-4">
                When creating an account on behalf of a business, institution,
                or other legal entity, you represent and warrant that you have
                the authority to bind that entity to these Terms. In such cases,
                &quot;you&quot; and &quot;your&quot; will refer to that entity.
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li>
                  You are responsible for maintaining the confidentiality of
                  your account credentials.
                </li>
                <li>
                  You are fully responsible for all activities that occur under
                  your account.
                </li>
                <li>
                  You must immediately notify us of any unauthorized use of your
                  account or any other breach of security.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold tracking-tight text-on-surface mb-4">
                3. Data Privacy and AI Usage
              </h2>
              <p className="mb-4">
                Our platform utilizes advanced artificial intelligence to
                process and analyze talent data. By using the Service, you
                acknowledge and agree to our data processing practices as
                outlined in our Privacy Policy.
              </p>
              <div className="bg-surface-container-low p-6 rounded-2xl mt-6 border border-outline-variant/15">
                <h3 className="text-base font-semibold text-on-surface mb-2">
                  Important AI Disclaimer
                </h3>
                <p className="text-sm">
                  The insights and scores generated by Talash Insight&apos;s AI
                  models are intended to assist, not replace, human
                  decision-making in the recruitment process. The Company does
                  not guarantee the absolute accuracy or predictive certainty of
                  these algorithmic outputs.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold tracking-tight text-on-surface mb-4">
                4. Intellectual Property Rights
              </h2>
              <p className="mb-4">
                Unless otherwise indicated, the Service is our proprietary
                property and all source code, databases, functionality,
                software, website designs, audio, video, text, photographs, and
                graphics on the Service (collectively, the &quot;Content&quot;)
                and the trademarks, service marks, and logos contained therein
                are owned or controlled by us or licensed to us.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold tracking-tight text-on-surface mb-4">
                5. Limitation of Liability
              </h2>
              <p className="mb-4">
                In no event will we or our directors, employees, or agents be
                liable to you or any third party for any direct, indirect,
                consequential, exemplary, incidental, special, or punitive
                damages, including lost profit, lost revenue, loss of data, or
                other damages arising from your use of the Service, even if we
                have been advised of the possibility of such damages.
              </p>
            </section>

            <section className="mt-12 pt-8 border-t border-outline-variant/15">
              <p className="text-sm italic">
                For any questions regarding these Terms, please contact our
                legal department at{" "}
                <a
                  href="mailto:legal@talashinsight.com"
                  className="text-primary hover:underline not-italic"
                >
                  legal@talashinsight.com
                </a>
                .
              </p>
            </section>
          </div>
        </article>
      </main>

      <PublicFooter />
    </div>
  );
}
